---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ceph-claim
  namespace: {{  .Release.Namespace  }}
spec:
  storageClassName: {{  .Values.nfsServer.storageclassName  }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs
  namespace: {{  .Release.Namespace  }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade,pre-delete"
spec:
  replicas: {{  .Values.nfsServer.replicas  }}
  exports:
  - name: share1
    server:
      accessMode: ReadWrite
      squash: "none"
    persistentVolumeClaim:
      claimName: nfs-ceph-claim
  annotations:
  #  key: value
