kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-fastdfs
  labels:
    {{- include "club-fastdfs.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistentVolume.storageClass }}
