apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
