apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- include "kube-state-metrics.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ template "kube-state-metrics.serviceAccountName" . }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: kube-state-metrics
          image: {{ template "kube-state-metrics.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.collectors.certificatesigningrequests }}
            - --collectors=certificatesigningrequests
            {{- end }}
            {{- if .Values.collectors.configmaps }}
            - --collectors=configmaps
            {{- end }}
            {{- if .Values.collectors.cronjobs }}
            - --collectors=cronjobs
            {{- end }}
            {{- if .Values.collectors.daemonsets }}
            - --collectors=daemonsets
            {{- end }}
            {{- if .Values.collectors.deployments }}
            - --collectors=deployments
            {{- end }}
            {{- if .Values.collectors.endpoints }}
            - --collectors=endpoints
            {{- end }}
            {{- if .Values.collectors.horizontalpodautoscalers }}
            - --collectors=horizontalpodautoscalers
            {{- end }}
            {{- if .Values.collectors.ingresses }}
            - --collectors=ingresses
            {{- end }}
            {{- if .Values.collectors.jobs }}
            - --collectors=jobs
            {{- end }}
            {{- if .Values.collectors.limitranges }}
            - --collectors=limitranges
            {{- end }}
            {{- if .Values.collectors.mutatingwebhookconfigurations }}
            - --collectors=mutatingwebhookconfigurations
            {{- end }}
            {{- if .Values.collectors.namespaces }}
            - --collectors=namespaces
            {{- end }}
            {{- if .Values.collectors.networkpolicies }}
            - --collectors=networkpolicies
            {{- end }}
            {{- if .Values.collectors.nodes }}
            - --collectors=nodes
            {{- end }}
            {{- if .Values.collectors.persistentvolumeclaims }}
            - --collectors=persistentvolumeclaims
            {{- end }}
            {{- if .Values.collectors.persistentvolumes }}
            - --collectors=persistentvolumes
            {{- end }}
            {{- if .Values.collectors.poddisruptionbudgets }}
            - --collectors=poddisruptionbudgets
            {{- end }}
            {{- if .Values.collectors.pods }}
            - --collectors=pods
            {{- end }}
            {{- if .Values.collectors.replicasets }}
            - --collectors=replicasets
            {{- end }}
            {{- if .Values.collectors.replicationcontrollers }}
            - --collectors=replicationcontrollers
            {{- end }}
            {{- if .Values.collectors.resourcequotas }}
            - --collectors=resourcequotas
            {{- end }}
            {{- if .Values.collectors.secrets }}
            - --collectors=secrets
            {{- end }}
            {{- if .Values.collectors.services }}
            - --collectors=services
            {{- end }}
            {{- if .Values.collectors.statefulsets }}
            - --collectors=statefulsets
            {{- end }}
            {{- if .Values.collectors.storageclasses }}
            - --collectors=storageclasses
            {{- end }}
            {{- if .Values.collectors.verticalpodautoscalers }}
            - --collectors=verticalpodautoscalers
            {{- end }}
            {{- if .Values.collectors.validatingwebhookconfigurations }}
            - --collectors=validatingwebhookconfigurations
            {{- end }}
            {{- if .Values.collectors.volumeattachments }}
            - --collectors=volumeattachments
            {{- end }}
            {{- if .Values.namespace }}
            - --namespace={{ .Values.namespace }}
            {{- end }}
            {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
